# Generated by Django 5.2.5 on 2025-08-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telephone_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verification_code', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('category', models.CharField(max_length=20, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percentage', models.IntegerField()),
                ('maximum_discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_units_per_customer', models.IntegerField()),
                ('single_use', models.BooleanField(default=True)),
                ('needed_item_quantity_to_use', models.IntegerField(default=1)),
                ('applicable_on_item_amount', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telephone_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verification_code', models.DecimalField(decimal_places=2, max_digits=4)),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.customer')),
            ],
        ),
    ]
