# Generated by Django 5.2.5 on 2025-08-10 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='items_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.items'),
        ),
    ]
