# Generated by Django 5.2.5 on 2025-08-12 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_coupons_items_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.coupons')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.customer')),
            ],
            options={
                'unique_together': {('customer', 'coupon')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='coupons',
            field=models.ManyToManyField(through='kiosk.CustomerCoupon', to='kiosk.coupons'),
        ),
    ]
