# Generated by Django 5.2.5 on 2025-08-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_remove_coupons_email_remove_coupons_telephone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
