# Generated by Django 5.2.5 on 2025-08-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_rename_customer_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupons',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='customercoupon',
            table='customer_coupons',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
