# Generated by Django 5.2.5 on 2025-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_rename_coupons_coupon_rename_customers_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
